# Generated by Django 5.2.7 on 2025-11-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_service_servicebooking_delete_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
